# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Create the KMS keys for end-to-end data encryption

Parameters:
  StudioRoleDataScienceArn:
    Type: String
    Description: The ARN of the environment-related DataScienceTeamAdministrator role
  
  StudioRoleMLOpsArn:
    Type: String
    Description: The ARN of the Data Scientist role
  
  VPCEndpointKMSId:
    Description: Id of the KMS VPC endpoint
    Type: String

Outputs:
    S3BucketKMSKeyArn:
      Description: KMS Key ARN for the S3 buckets
      Value: !GetAtt S3BucketKMSKey.Arn

    S3BucketKMSKeyId:
      Description: KMS Key Id for the S3 buckets
      Value: !Ref S3BucketKMSKey

    SagemakerEBSKMSKeyArn:
      Description: KMS Key ARN for the SageMaker workloads EBS volumes
      Value: !GetAtt SagemakerEBSKMSKey.Arn
  
    SagemakerEBSKMSKeyId:
      Description: KMS Key Id for the SageMaker workloads EBS volumes
      Value: !Ref SagemakerEBSKMSKey

    SageMakerStudioStorageKMSKeyArn:
      Description: KMS Key Id for the SageMaker Studio EFS and EBS file systems
      Value: !GetAtt SageMakerStudioStorageKMSKey.Arn

    SageMakerStudioStorageKMSKeyId:
      Description: KMS Key Id for the SageMaker Studio EFS and EBS file systems
      Value: !Ref SageMakerStudioStorageKMSKey

Resources:
  SagemakerEBSKMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: Generated KMS Key for SageMaker workload EBS volume encryption
      EnableKeyRotation: true
      Enabled: true
      KeyPolicy:
        Version: 2012-10-17
        Id: KmsKey-SageMakerEBSKey
        Statement:
          - Sid: "Enable IAM User Permissions"
            Action:
              - 'kms:*'
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Resource: '*'
          - Sid: Allow use of the key for Studio roles
            Effect: Allow
            Principal:
              AWS: 
                - !Ref StudioRoleDataScienceArn
                - !Ref StudioRoleMLOpsArn
            Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:DescribeKey
            Resource: "*"
          - Sid: Allow use of the key with AWS services
            Effect: Allow
            Principal:
              AWS: 
                - !Ref StudioRoleDataScienceArn
                - !Ref StudioRoleMLOpsArn
            Action:
            - kms:CreateGrant
            - kms:ListGrants
            - kms:RevokeGrant
            Resource: "*"
            Condition:
              Bool:
                kms:GrantIsForAWSResource: 'true'
      Tags:
        - Key: project
          Value: !Sub sagemaker-admin-workshop:${AWS::Region}:${AWS::AccountId}

  SagemakerEBSKMSKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub "alias/sagemaker-admin-workshop-${AWS::Region}-${AWS::AccountId}-kms-ebs"
      TargetKeyId: !Ref SagemakerEBSKMSKey

  SageMakerStudioStorageKMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: Generated KMS Key for SageMaker Studio EFS and EBS file systems
      EnableKeyRotation: true
      Enabled: true
      KeyPolicy:
        Version: 2012-10-17
        Id: KmsKey-SageMakerStudioKey
        Statement:
          - Sid: "Enable IAM User Permissions"
            Action:
              - 'kms:*'
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Resource: '*'
          - Sid: Allow use of the key for Studio roles
            Effect: Allow
            Principal:
              AWS: 
                - !Ref StudioRoleDataScienceArn
                - !Ref StudioRoleMLOpsArn
            Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:DescribeKey
            Resource: "*"
          - Sid: Allow use of the key with AWS services
            Effect: Allow
            Principal:
              AWS: 
                - !Ref StudioRoleDataScienceArn
                - !Ref StudioRoleMLOpsArn
            Action:
            - kms:CreateGrant
            - kms:ListGrants
            - kms:RevokeGrant
            Resource: "*"
            Condition:
              Bool:
                kms:GrantIsForAWSResource: 'true'
      Tags:
        - Key: project
          Value: !Sub sagemaker-admin-workshop:${AWS::Region}:${AWS::AccountId}

  SageMakerStudioStorageKMSKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub "alias/sagemaker-admin-workshop-${AWS::Region}-${AWS::AccountId}-kms-efs"
      TargetKeyId: !Ref SageMakerStudioStorageKMSKey

  S3BucketKMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      EnableKeyRotation: true
      Description: KMS key for S3 buckets for the Data Science environment
      KeyPolicy:
        Id: KmsKey-S3Key
        Version: 2012-10-17
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: Allow
            Action: 
              - 'kms:*'
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: 
                - !Ref StudioRoleDataScienceArn
                - !Ref StudioRoleMLOpsArn
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
          - Sid: DenyNoVPCE
            Effect: Deny
            Principal: '*'
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:sourceVpce': !Ref VPCEndpointKMSId
              Bool:
                'aws:ViaAWSService': 'false' #Allow connection from CodeCommit to copy artifacts
      Tags:
        - Key: project
          Value: !Sub sagemaker-admin-workshop:${AWS::Region}:${AWS::AccountId}

  S3BucketKMSKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub "alias/sagemaker-admin-workshop-${AWS::Region}-${AWS::AccountId}-kms-s3"
      TargetKeyId: !Ref S3BucketKMSKey

  # Save KMS key ARNs as SSM parameters
  S3BucketKMSKeyArnSSM:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub sagemaker-admin-workshop-${AWS::Region}-${AWS::AccountId}-kms-s3-key-arn
      Type: String
      Value: !GetAtt S3BucketKMSKey.Arn
      Description: Environment S3 buckets KMS key
  
  SagemakerEBSKMSKeyArnSSM:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub sagemaker-admin-workshop-${AWS::Region}-${AWS::AccountId}-kms-ebs-key-arn
      Type: String
      Value: !GetAtt 
        - SagemakerEBSKMSKey
        - Arn
      Description: EBS KMS key to encrypt SageMaker workload instance volume

  SageMakerStudioStorageKMSKeyArnSSM:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub sagemaker-admin-workshop-${AWS::Region}-${AWS::AccountId}-kms-efs-key-arn
      Type: String
      Value: !GetAtt 
        - SageMakerStudioStorageKMSKey
        - Arn
      Description: KMS key to encrypt SageMaker EFS and EBS file systems